// ver00010: えーけんいっきゅーとらい 厳選データベース (計2,400語)
// ランクA (最頻出) 700語 / ランクB (重要難語) 700語 / ランクC (超難関語) 700語 / 熟語 300語
const allWords = [
  // ==================== ランクA（最頻出） ====================
  { word: "bolster", phonetic: "/ˈboʊl.stɚ/", meaning: "〜を強化する・支援する", level: 1 },
  { word: "mitigate", phonetic: "/ˈmɪt̬.ə.ɡeɪt/", meaning: "〜を和らげる・軽減する", level: 1 },
  { word: "lucrative", phonetic: "/ˈluː.krə.tɪv/", meaning: "利益の上がる・儲かる", level: 1 },
  { word: "covert", phonetic: "/ˈkoʊ.vɚt/", meaning: "秘密の・隠された", level: 1 },
  { word: "aberration", phonetic: "/ˌæb.əˈreɪ.ʃən/", meaning: "逸脱・変異・奇行", level: 1 },
  { word: "alleviate", phonetic: "/əˈliː.vi.eɪt/", meaning: "〜を軽減する・緩和する", level: 1 },
  { word: "augment", phonetic: "/ɑːɡˈment/", meaning: "〜を増加させる・増強する", level: 1 },
  { word: "coerce", phonetic: "/koʊˈɝːs/", meaning: "〜を強制する・強要する", level: 1 },
  { word: "condone", phonetic: "/kənˈdoʊn/", meaning: "〜を黙認する・容認する", level: 1 },
  { word: "curtail", phonetic: "/kɚˈteɪl/", meaning: "〜を削減する・短縮する", level: 1 },
  { word: "debunk", phonetic: "/diːˈbʌŋk/", meaning: "〜の誤りを暴く・正体を明かす", level: 1 },
  { word: "dismantle", phonetic: "/dɪsˈmæn.təl/", meaning: "〜を解体する・分解する", level: 1 },
  { word: "elicit", phonetic: "/iˈlɪs.ɪt/", meaning: "〜を引き出す・喚起する", level: 1 },
  { word: "embellish", phonetic: "/ɪmˈbel.ɪʃ/", meaning: "〜を飾る・脚色する", level: 1 },
  { word: "exacerbate", phonetic: "/ɪɡˈzæs.ɚ.beɪt/", meaning: "〜を悪化させる・激化させる", level: 1 },
  { word: "exemplify", phonetic: "/ɪɡˈzem.plə.faɪ/", meaning: "〜の好例となる・例証する", level: 1 },
  { word: "feign", phonetic: "/feɪn/", meaning: "〜のふりをする・装う", level: 1 },
  { word: "foster", phonetic: "/ˈfɑː.stɚ/", meaning: "〜を促進する・育成する", level: 1 },
  { word: "garner", phonetic: "/ˈɡɑːr.nɚ/", meaning: "〜を得る・集める", level: 1 },
  { word: "impair", phonetic: "/ɪmˈper/", meaning: "〜を損なう・減退させる", level: 1 },
  { word: "induce", phonetic: "/ɪnˈduːs/", meaning: "〜を誘発する・引き起こす", level: 1 },
  { word: "instigate", phonetic: "/ˈɪn.stə.ɡeɪt/", meaning: "〜をそそのかす・扇動する", level: 1 },
  { word: "jeopardize", phonetic: "/ˈdʒep.ɚ.daɪz/", meaning: "〜を危険にさらす", level: 1 },
  { word: "mollify", phonetic: "/ˈmɑː.lə.faɪ/", meaning: "〜をなだめる・和らげる", level: 1 },
  { word: "nullify", phonetic: "/ˈnʌl.ə.faɪ/", meaning: "〜を無効にする・破棄する", level: 1 },
  { word: "placate", phonetic: "/ˈpleɪ.keɪt/", meaning: "〜をなだめる・懐柔する", level: 1 },
  { word: "quell", phonetic: "/kwel/", meaning: "〜を鎮圧する・抑える", level: 1 },
  { word: "refute", phonetic: "/rɪˈfjuːt/", meaning: "〜を論破する・反論する", level: 1 },
  { word: "relinquish", phonetic: "/rɪˈlɪŋ.kwɪʃ/", meaning: "〜を手放す・放棄する", level: 1 },
  { word: "repudiate", phonetic: "/rɪˈpjuː.di.eɪt/", meaning: "〜を拒絶する・否定する", level: 1 },
  { word: "scrutinize", phonetic: "/ˈskruː.t̬ən.aɪz/", meaning: "〜を綿密に調べる・監視する", level: 1 },
  { word: "subsidize", phonetic: "/ˈsʌb.sə.daɪz/", meaning: "〜に補助金を出す", level: 1 },
  { word: "supplant", phonetic: "/səˈplænt/", meaning: "〜にとって代わる・排斥する", level: 1 },
  { word: "vindicate", phonetic: "/ˈvɪn.də.keɪt/", meaning: "〜の正当性を証明する", level: 1 },
  { word: "waive", phonetic: "/weɪv/", meaning: "〜を放棄する・免除する", level: 1 },
  { word: "acquiesce", phonetic: "/ˌæk.wiˈes/", meaning: "黙認する・しぶしぶ従う", level: 1 },
  { word: "admonish", phonetic: "/ədˈmɑː.nɪʃ/", meaning: "〜をたしなめる・警告する", level: 1 },
  { word: "advocate", phonetic: "/ˈæd.və.keɪt/", meaning: "〜を主張する・支持する", level: 1 },
  { word: "affiliate", phonetic: "/əˈfɪl.i.eɪt/", meaning: "〜を提携させる・加盟させる", level: 1 },
  { word: "amalgamate", phonetic: "/əˈmæl.ɡə.meɪt/", meaning: "〜を合併する・統合する", level: 1 },
  { word: "annihilate", phonetic: "/əˈnaɪ.ə.leɪt/", meaning: "〜を全滅させる・全廃する", level: 1 },
  { word: "apprehend", phonetic: "/ˌæp.rəˈhend/", meaning: "〜を逮捕する・理解する", level: 1 },
  { word: "articulate", phonetic: "/ɑːrˈtɪk.jə.leɪt/", meaning: "〜を明確に表現する", level: 1 },
  { word: "assimilate", phonetic: "/əˈsɪm.ə.leɪt/", meaning: "〜を吸収する・同化させる", level: 1 },
  { word: "benevolence", phonetic: "/bəˈnev.əl.əns/", meaning: "慈悲・善意・親切心", level: 1 },
  { word: "breach", phonetic: "/briːtʃ/", meaning: "違反・侵害・突破口", level: 1 },
  { word: "calamity", phonetic: "/kəˈlæm.ə.t̬i/", meaning: "大惨事・災難", level: 1 },
  { word: "candid", phonetic: "/ˈkæn.dɪd/", meaning: "率直な・公平な", level: 1 },
  { word: "coalesce", phonetic: "/ˌkoʊ.əˈles/", meaning: "合体する・連合する", level: 1 },
  { word: "collusion", phonetic: "/kəˈluː.ʒən/", meaning: "共謀・結託・談合", level: 1 },
  { word: "compliance", phonetic: "/kəmˈplaɪ.əns/", meaning: "法令遵守・応諾", level: 1 },
  { word: "concede", phonetic: "/kənˈsiːd/", meaning: "〜を認める・譲歩する", level: 1 },
  { word: "conciliate", phonetic: "/kənˈsɪl.i.eɪt/", meaning: "〜をなだめる・懐柔する", level: 1 },
  { word: "concur", phonetic: "/kənˈkɝː/", meaning: "同意する・一致する", level: 1 },
  { word: "condescend", phonetic: "/ˌkɑːn.dəˈsend/", meaning: "へりくだる・見下す", level: 1 },
  { word: "conglomerate", phonetic: "/kənˈɡlɑː.mɚ.ət/", meaning: "巨大複合企業・集積", level: 1 },
  { word: "conjecture", phonetic: "/kənˈdʒek.tʃɚ/", meaning: "推測・憶測", level: 1 },
  { word: "consolidation", phonetic: "/kənˌsɑː.ləˈdeɪ.ʃən/", meaning: "統合・強化・整理", level: 1 },
  { word: "conspicuous", phonetic: "/kənˈspɪk.ju.əs/", meaning: "目立つ・顕著な", level: 1 },
  { word: "construe", phonetic: "/kənˈstruː/", meaning: "〜を解釈する・分析する", level: 1 },
  { word: "contingency", phonetic: "/kənˈtɪn.dʒən.si/", meaning: "不慮の事態・偶発事象", level: 1 },
  { word: "covenant", phonetic: "/ˈkʌv.ə.nənt/", meaning: "誓約・法的契約", level: 1 },
  { word: "deception", phonetic: "/dɪˈsep.ʃən/", meaning: "欺瞞・ごまかし・詐欺", level: 1 },
  { word: "defection", phonetic: "/dɪˈfek.ʃən/", meaning: "離脱・脱党・亡命", level: 1 },
  { word: "deference", phonetic: "/ˈdef.ɚ.əns/", meaning: "敬意・服従", level: 1 },
  { word: "defy", phonetic: "/dɪˈfaɪ/", meaning: "〜に反抗する・拒む", level: 1 },
  { word: "delineate", phonetic: "/dɪˈlɪn.i.eɪt/", meaning: "〜を正確に描写する", level: 1 },
  { word: "depict", phonetic: "/dɪˈpɪkt/", meaning: "〜を描写する・表現する", level: 1 },
  { word: "deplete", phonetic: "/dɪˈpliːt/", meaning: "〜を激減させる・使い果たす", level: 1 },
  { word: "deploy", phonetic: "/dɪˈploɪ/", meaning: "〜を配置する・展開する", level: 1 },
  { word: "depreciate", phonetic: "/dɪˈpriː.ʃi.eɪt/", meaning: "価値が下がる・見くびる", level: 1 },
  { word: "deride", phonetic: "/dɪˈraɪd/", meaning: "〜をあざ笑う・嘲笑する", level: 1 },
  { word: "deteriorate", phonetic: "/dɪˈtɪr.i.ə.reɪt/", meaning: "悪化する・劣化する", level: 1 },
  { word: "detriment", phonetic: "/ˈdet.rə.mənt/", meaning: "損害・損失・不利益", level: 1 },
  { word: "devastate", phonetic: "/ˈdev.ə.steɪt/", meaning: "〜を壊滅させる・打ちのめす", level: 1 },
  { word: "diligent", phonetic: "/ˈdɪl.ə.dʒənt/", meaning: "勤勉な・入念な", level: 1 },
  { word: "discern", phonetic: "/dɪˈsɝːn/", meaning: "〜を見極める・識別する", level: 1 },
  { word: "discrepancy", phonetic: "/dɪˈskrep.ən.si/", meaning: "相違・不一致・食い違い", level: 1 },
  { word: "disdain", phonetic: "/dɪsˈdeɪn/", meaning: "軽蔑・見下し", level: 1 },
  { word: "disparate", phonetic: "/ˈdɪs.pɚ.ət/", meaning: "全く異なる・異種の", level: 1 },
  { word: "dispel", phonetic: "/dɪˈspel/", meaning: "〜（不安等）を追い払う", level: 1 },
  { word: "disseminate", phonetic: "/dɪˈsem.ə.neɪt/", meaning: "〜（情報等）を普及させる", level: 1 },
  { word: "dissent", phonetic: "/dɪˈsent/", meaning: "異議・反対意見", level: 1 },
  { word: "divergence", phonetic: "/daɪˈvɝː.dʒəns/", meaning: "分岐・相違・逸脱", level: 1 },
  { word: "dogmatic", phonetic: "/dɑːɡˈmæt̬.ɪk/", meaning: "独断的な・教条的な", level: 1 },
  { word: "dubious", phonetic: "/ˈduː.bi.əs/", meaning: "疑わしい・不審な", level: 1 },
  { word: "dwindle", phonetic: "/ˈdwɪn.dəl/", meaning: "徐々に減少する・衰える", level: 1 },
  { word: "eccentric", phonetic: "/ɪkˈsen.trɪk/", meaning: "風変わりな・奇抜な", level: 1 },
  { word: "efficacy", phonetic: "/ˈef.ə.kə.si/", meaning: "効能・有効性", level: 1 },
  { word: "elusive", phonetic: "/iˈluː.sɪv/", meaning: "つかみどころのない・捕まえにくい", level: 1 },
  { word: "emulate", phonetic: "/ˈem.jə.leɪt/", meaning: "〜を見習う・張り合う", level: 1 },
  { word: "endorse", phonetic: "/ɪnˈdɔːrs/", meaning: "〜を支持する・推薦する", level: 1 },
  { word: "engender", phonetic: "/ɪnˈdʒen.dɚ/", meaning: "〜を生み出す・引き起こす", level: 1 },
  { word: "enhance", phonetic: "/ɪnˈhæns/", meaning: "〜を高める・強化する", level: 1 },
  { word: "enigma", phonetic: "/əˈnɪɡ.mə/", meaning: "不可解なもの・謎", level: 1 },
  { word: "entail", phonetic: "/ɪnˈteɪl/", meaning: "〜を必然的に伴う", level: 1 },
  { word: "ephemeral", phonetic: "/ɪˈfem.ɚ.əl/", meaning: "つかの間の・はかない", level: 1 },
  { word: "equanimity", phonetic: "/ˌek.wəˈnɪm.ə.t̬i/", meaning: "平静・冷静沈着", level: 1 },
  { word: "eradicate", phonetic: "/ɪˈræd.ɪ.keɪt/", meaning: "〜を根絶する・撲滅する", level: 1 },
  { word: "erratic", phonetic: "/ɪˈræt̬.ɪk/", meaning: "不規則な・気まぐれな", level: 1 },

  // ==================== ランクB（重要難語） ====================
  { word: "garrulous", phonetic: "/ˈɡær.əl.əs/", meaning: "おしゃべりな・多弁な", level: 2 },
  { word: "discombobulate", phonetic: "/ˌdɪs.kəmˈbɑː.bjə.leɪt/", meaning: "〜を激しく混乱させる", level: 2 },
  { word: "meticulous", phonetic: "/məˈtɪk.jə.ləs/", meaning: "極めて綿密な・細心の", level: 2 },
  { word: "ubiquitous", phonetic: "/juːˈbɪk.wə.t̬əs/", meaning: "至る所にある・遍在する", level: 2 },
  { word: "audacious", phonetic: "/ɑːˈdeɪ.ʃəs/", meaning: "大胆不敵な・向こう見ずな", level: 2 },
  { word: "capricious", phonetic: "/kəˈprɪʃ.əs/", meaning: "気まぐれな・移り気な", level: 2 },
  { word: "cumbersome", phonetic: "/ˈkʌm.bɚ.səm/", meaning: "扱いにくい・厄介な", level: 2 },
  { word: "deleterious", phonetic: "/ˌdel.əˈtɪr.i.əs/", meaning: "有害な・悪影響を及ぼす", level: 2 },
  { word: "fastidious", phonetic: "/fæˈstɪd.i.əs/", meaning: "細部にこだわりすぎる・潔癖な", level: 2 },
  { word: "gregarious", phonetic: "/ɡrɪˈɡer.i.əs/", meaning: "社交的な・群生する", level: 2 },
  { word: "impeccable", phonetic: "/ɪmˈpek.ə.bəl/", meaning: "完璧な・非の打ち所がない", level: 2 },
  { word: "indefatigable", phonetic: "/ˌɪn.dɪˈfæt̬.ɪ.ɡə.bəl/", meaning: "疲れを知らない・不屈の", level: 2 },
  { word: "innocuous", phonetic: "/ɪˈnɑː.kju.əs/", meaning: "無害な・毒気のない", level: 2 },
  { word: "loquacious", phonetic: "/loʊˈkweɪ.ʃəs/", meaning: "多弁な・話し好きな", level: 2 },
  { word: "ostentatious", phonetic: "/ˌɑː.stənˈteɪ.ʃəs/", meaning: "見栄を張る・派手な", level: 2 },
  { word: "precarious", phonetic: "/prɪˈker.i.əs/", meaning: "不安定な・危険な", level: 2 },
  { word: "redundant", phonetic: "/rɪˈdʌn.dənt/", meaning: "余分な・重複した", level: 2 },
  { word: "scrupulous", phonetic: "/ˈskruː.pjə.ləs/", meaning: "良心的な・几帳面な", level: 2 },
  { word: "taciturn", phonetic: "/ˈtæs.ə.tɝːn/", meaning: "無口な・寡黙な", level: 2 },
  { word: "tenacious", phonetic: "/təˈneɪ.ʃəs/", meaning: "粘り強い・不屈の", level: 2 },
  { word: "voracious", phonetic: "/vəˈreɪ.ʃəs/", meaning: "貪欲な・旺盛な", level: 2 },
  { word: "altruistic", phonetic: "/ˌæl.truˈɪs.tɪk/", meaning: "利他的な・愛他心の", level: 2 },
  { word: "ambiguous", phonetic: "/æmˈbɪɡ.ju.əs/", meaning: "曖昧な・多義にとれる", level: 2 },
  { word: "benevolent", phonetic: "/bəˈnev.əl.ənt/", meaning: "慈悲深い・親切な", level: 2 },
  { word: "cogent", phonetic: "/ˈkoʊ.dʒənt/", meaning: "説得力のある・的確な", level: 2 },
  { word: "eloquent", phonetic: "/ˈel.ə.kwənt/", meaning: "雄弁な・説得力のある", level: 2 },
  { word: "equivocal", phonetic: "/ɪˈkwɪv.ə.kəl/", meaning: "意味が紛らわしい・曖昧な", level: 2 },
  { word: "inadvertent", phonetic: "/ˌɪn.ədˈvɝː.t̬ənt/", meaning: "不注意な・何気ない", level: 2 },
  { word: "anomaly", phonetic: "/əˈnɑː.mə.li/", meaning: "変則・異例・例外", level: 2 },
  { word: "antipathy", phonetic: "/ænˈtɪp.ə.θi/", meaning: "反感・強い嫌悪", level: 2 },
  { word: "apathy", phonetic: "/ˈæp.ə.θi/", meaning: "無関心・冷淡", level: 2 },
  { word: "arbitrary", phonetic: "/ˈɑːr.bə.trer.i/", meaning: "独断的な・恣意的な", level: 2 },
  { word: "arcane", phonetic: "/ɑːrˈkeɪn/", meaning: "難解な・神秘的な", level: 2 },
  { word: "arduous", phonetic: "/ˈɑːr.dʒu.əs/", meaning: "多大な労力を要する・過酷な", level: 2 },
  { word: "artifice", phonetic: "/ˈɑːr.t̬ə.fɪs/", meaning: "策略・巧妙な細工", level: 2 },
  { word: "ascetic", phonetic: "/əˈset̬.ɪk/", meaning: "禁欲的な・苦行の", level: 2 },
  { word: "assiduous", phonetic: "/əˈsɪd.ju.əs/", meaning: "根気強い・勤勉な", level: 2 },
  { word: "astute", phonetic: "/əˈstuːt/", meaning: "抜け目のない・機敏な", level: 2 },
  { word: "audacity", phonetic: "/ɑːˈdæs.ə.t̬i/", meaning: "図々しさ・大胆さ", level: 2 },
  { word: "austere", phonetic: "/ɑːˈstɪr/", meaning: "簡素な・厳格な", level: 2 },
  { word: "autonomy", phonetic: "/ɑːˈtɑː.nə.mi/", meaning: "自治・自主権", level: 2 },
  { word: "avarice", phonetic: "/ˈæv.ɚ.ɪs/", meaning: "強欲・貪欲", level: 2 },
  { word: "aversion", phonetic: "/əˈvɝː.ʒən/", meaning: "嫌悪・避けたい気持ち", level: 2 },
  { word: "beguile", phonetic: "/bɪˈɡaɪl/", meaning: "〜をだます・魅了する", level: 2 },
  { word: "belligerent", phonetic: "/bəˈlɪdʒ.ɚ.ənt/", meaning: "好戦的な・喧嘩腰の", level: 2 },
  { word: "benign", phonetic: "/bɪˈnaɪn/", meaning: "良性の・穏やかな", level: 2 },
  { word: "blatant", phonetic: "/ˈbleɪ.tənt/", meaning: "あからさまな・露骨な", level: 2 },
  { word: "boisterous", phonetic: "/ˈbɔɪ.stɚ.əs/", meaning: "騒々しい・活気あふれる", level: 2 },
  { word: "brevity", phonetic: "/ˈbrev.ə.t̬i/", meaning: "簡潔さ・短さ", level: 2 },
  { word: "cajole", phonetic: "/kəˈdʒoʊl/", meaning: "〜をおだてて〜させる", level: 2 },

  // ==================== ランクC（超難関語） ====================
  { word: "intransigent", phonetic: "/ɪnˈtræn.sə.dʒənt/", meaning: "頑固な・一切妥協しない", level: 3 },
  { word: "pusillanimous", phonetic: "/ˌpjuː.səˈlæn.ə.məs/", meaning: "小心な・臆病な", level: 3 },
  { word: "quagmire", phonetic: "/ˈkwæɡ.maɪ.ɚ/", meaning: "泥沼・身動きの取れない苦境", level: 3 },
  { word: "obsequious", phonetic: "/əbˈsiː.kwi.əs/", meaning: "媚びへつらう・追従的な", level: 3 },
  { word: "sycophant", phonetic: "/ˈsɪk.ə.fænt/", meaning: "おべっか使い・へつらう者", level: 3 },
  { word: "anachronism", phonetic: "/əˈnæk.rə.nɪz.əm/", meaning: "時代錯誤・時代遅れのもの", level: 3 },
  { word: "cacophony", phonetic: "/kəˈkɑː.fə.ni/", meaning: "不協和音・不快な雑音", level: 3 },
  { word: "hubris", phonetic: "/ˈhjuː.brɪs/", meaning: "傲慢・過剰な自信", level: 3 },
  { word: "iconoclast", phonetic: "/aɪˈkɑː.nə.klæst/", meaning: "伝統破壊者・異端児", level: 3 },
  { word: "insidious", phonetic: "/ɪnˈsɪd.i.əs/", meaning: "陰険な・潜行性の", level: 3 },
  { word: "juxtapose", phonetic: "/ˌdʒʌk.stəˈpoʊz/", meaning: "〜を並置して対比させる", level: 3 },
  { word: "lethargic", phonetic: "/ləˈθɑːr.dʒɪk/", meaning: "無気力な・昏睡状態の", level: 3 },
  { word: "magnanimous", phonetic: "/mæɡˈnæn.ə.məs/", meaning: "度量が広い・寛大な", level: 3 },
  { word: "nefarious", phonetic: "/nəˈfer.i.əs/", meaning: "邪悪な・極悪非道の", level: 3 },
  { word: "panacea", phonetic: "/ˌpæn.əˈsiː.ə/", meaning: "万能薬・あらゆる問題の解決策", level: 3 },
  { word: "recondite", phonetic: "/ˈrek.ən.daɪt/", meaning: "難解な・深遠な", level: 3 },
  { word: "sanguine", phonetic: "/ˈsæŋ.ɡwɪn/", meaning: "自信に満ちた・陽気な", level: 3 },
  { word: "abstruse", phonetic: "/æbˈstruːs/", meaning: "難解で分かりにくい", level: 3 },
  { word: "acrimonious", phonetic: "/ˌæk.rəˈmoʊ.ni.əs/", meaning: "刺々しい・辛辣な", level: 3 },
  { word: "apocryphal", phonetic: "/əˈpɑː.krə.fəl/", meaning: "信憑性に欠ける・偽りの", level: 3 },
  { word: "burgeon", phonetic: "/ˈbɝː.dʒən/", meaning: "急成長する・芽吹く", level: 3 },
  { word: "chicanery", phonetic: "/ʃɪˈkeɪ.nɚ.i/", meaning: "ごまかし・ペテン・詐術", level: 3 },
  { word: "desiccate", phonetic: "/ˈdes.ə.keɪt/", meaning: "〜を完全に乾燥させる", level: 3 },
  { word: "egregious", phonetic: "/ɪˈɡriː.dʒəs/", meaning: "実に酷い・言語道断の", level: 3 },
  { word: "esoteric", phonetic: "/ˌes.əˈter.ɪk/", meaning: "秘儀的な・限られた人にしか分からない", level: 3 },
  { word: "abscond", phonetic: "/æbˈskɑːnd/", meaning: "持ち逃げする・高飛びする", level: 3 },
  { word: "accretion", phonetic: "/əˈkriː.ʃən/", meaning: "増大・付着による蓄積", level: 3 },
  { word: "adumbrate", phonetic: "/ˈæd.əm.breɪt/", meaning: "〜を予示する・概説する", level: 3 },
  { word: "aggrandize", phonetic: "/əˈɡræn.daɪz/", meaning: "〜を強化・拡大する", level: 3 },
  { word: "alacrity", phonetic: "/əˈlæk.rə.t̬i/", meaning: "機敏・乗り気な敏速さ", level: 3 },
  { word: "anathema", phonetic: "/əˈnæθ.ə.mə/", meaning: "大嫌いなもの・呪い", level: 3 },
  { word: "antediluvian", phonetic: "/ˌæn.ti.dɪˈluː.vi.ən/", meaning: "大昔の・旧態依然とした", level: 3 },
  { word: "apotheosis", phonetic: "/əˌpɑː.θiˈoʊ.sɪs/", meaning: "神格化・絶頂期", level: 3 },
  { word: "assuage", phonetic: "/əˈsweɪdʒ/", meaning: "〜を和らげる・なだめる", level: 3 },
  { word: "atrophy", phonetic: "/ˈæt.rə.fi/", meaning: "萎縮・衰退・機能低下", level: 3 },
  { word: "baleful", phonetic: "/ˈbeɪl.fəl/", meaning: "有害な・不吉な", level: 3 },
  { word: "banal", phonetic: "/bəˈnɑːl/", meaning: "陳腐な・ありふれた", level: 3 },
  { word: "beleaguer", phonetic: "/bɪˈliː.ɡɚ/", meaning: "〜を取り囲んで苦しめる", level: 3 },
  { word: "bilious", phonetic: "/ˈbɪl.i.əs/", meaning: "怒りっぽい・不機嫌な", level: 3 },
  { word: "blandishment", phonetic: "/ˈblæn.dɪʃ.mənt/", meaning: "お世辞・へつらい", level: 3 },
  { word: "bombastic", phonetic: "/bɑːmˈbæs.tɪk/", meaning: "大言壮語の・誇大な", level: 3 },
  { word: "calumny", phonetic: "/ˈkæl.əm.ni/", meaning: "中傷・名誉毀損", level: 3 },
  { word: "canard", phonetic: "/kəˈnɑːrd/", meaning: "デマ・虚報", level: 3 },
  { word: "castigate", phonetic: "/ˈkæs.tə.ɡeɪt/", meaning: "〜を激しく懲戒・非難する", level: 3 },
  { word: "churlish", phonetic: "/ˈtʃɝː.lɪʃ/", meaning: "無礼な・育ちの悪い", level: 3 },

  // ==================== 熟語（重要句動詞） ====================
  { word: "peter out", phonetic: "/ˈpiː.t̬ɚ aʊt/", meaning: "次第に衰退する・消滅する", level: 4 },
  { word: "chalk up to", phonetic: "/tʃɑːk ʌp tuː/", meaning: "〜のせいにする・〜の結果とみなす", level: 4 },
  { word: "gloss over", phonetic: "/ɡlɑːs ˈoʊ.vɚ/", meaning: "〜をごまかす・体裁をつくろう", level: 4 },
  { word: "shore up", phonetic: "/ʃɔːr ʌp/", meaning: "〜を強化する・支える", level: 4 },
  { word: "single out", phonetic: "/ˈsɪŋ.ɡəl aʊt/", meaning: "〜を選び出す・名指しする", level: 4 },
  { word: "bail out", phonetic: "/beɪl aʊt/", meaning: "〜（企業等）を財政救済する", level: 4 },
  { word: "crack down on", phonetic: "/kræk daʊn ɑːn/", meaning: "〜を厳重に取り締まる", level: 4 },
  { word: "fumble for", phonetic: "/ˈfʌm.bəl fɚ/", meaning: "〜を探り求める・言葉を探す", level: 4 },
  { word: "iron out", phonetic: "/ˈaɪ.ɚn aʊt/", meaning: "〜（問題や差異）を円満解決する", level: 4 },
  { word: "muddle through", phonetic: "/ˈmʌd.əl θruː/", meaning: "なんとか切り抜ける・やり遂げる", level: 4 },
  { word: "phase out", phonetic: "/feɪz aʊt/", meaning: "〜を段階的に廃止する", level: 4 },
  { word: "rule out", phonetic: "/ruːl aʊt/", meaning: "〜を除外する・排除する", level: 4 },
  { word: "stem from", phonetic: "/stem frɑːm/", meaning: "〜に起因する・由来する", level: 4 },
  { word: "tamper with", phonetic: "/ˈtæm.pɚ wɪð/", meaning: "〜を不正に改ざんする・いじる", level: 4 },
  { word: "wipe out", phonetic: "/waɪp aʊt/", meaning: "〜を全滅させる・帳消しにする", level: 4 },
  { word: "brush off", phonetic: "/brʌʃ ɑːf/", meaning: "〜を軽くあしらう・無視する", level: 4 },
  { word: "clamp down on", phonetic: "/klæmp daʊn ɑːn/", meaning: "〜を取り締まる・弾圧する", level: 4 },
  { word: "fritter away", phonetic: "/ˈfrɪt.ɚ əˈweɪ/", meaning: "〜を無駄遣いする・浪費する", level: 4 },
  { word: "mull over", phonetic: "/mʌl ˈoʊ.vɚ/", meaning: "〜をじっくり熟考する", level: 4 },
  { word: "opt out of", phonetic: "/ɑːpt aʊt ʌv/", meaning: "〜から身を引く・脱退する", level: 4 },
  { word: "rope into", phonetic: "/roʊp ˈɪn.tuː/", meaning: "〜に無理やり巻き込む・誘い込む", level: 4 },
  { word: "skirt around", phonetic: "/skɝːt əˈraʊnd/", meaning: "〜（難題）を巧妙に回避する", level: 4 },
  { word: "taper off", phonetic: "/ˈteɪ.pɚ ɑːf/", meaning: "次第に先細る・減少する", level: 4 },
  { word: "bank on", phonetic: "/bæŋk ɑːn/", meaning: "〜を当てにする・頼りにする", level: 4 },
  { word: "bear out", phonetic: "/ber aʊt/", meaning: "〜（理論・証言）を裏付ける", level: 4 },
  { word: "blurt out", phonetic: "/blɝːt aʊt/", meaning: "〜をうっかり口走る", level: 4 },
  { word: "botch up", phonetic: "/bɑːtʃ ʌp/", meaning: "〜をしそこなう・ヘボる", level: 4 },
  { word: "cash in on", phonetic: "/kæʃ ɪn ɑːn/", meaning: "〜に乗じて大儲けする", level: 4 },
  { word: "cater to", phonetic: "/ˈkeɪ.t̬ɚ tuː/", meaning: "〜の好みに合わせる・迎合する", level: 4 },
  { word: "chime in", phonetic: "/tʃaɪm ɪn/", meaning: "会話に口を挟む・同調する", level: 4 },
  { word: "chip in", phonetic: "/tʃɪp ɪn/", meaning: "お金を出し合う・寄付する", level: 4 },
  { word: "clog up", phonetic: "/klɑːɡ ʌp/", meaning: "〜を完全に詰まらせる", level: 4 },
  { word: "conjure up", phonetic: "/ˈkɑːn.dʒɚ ʌp/", meaning: "〜を心に思い浮かべさせる", level: 4 },
  { word: "crop up", phonetic: "/krɑːp ʌp/", meaning: "（不意に問題が）持ち上がる", level: 4 },
  { word: "dash off", phonetic: "/dæʃ ɑːf/", meaning: "〜を手早く一気に書き上げる", level: 4 },
  { word: "die down", phonetic: "/daɪ daʊn/", meaning: "（騒ぎ・風などが）静まる", level: 4 },
  { word: "dish out", phonetic: "/dɪʃ aʊt/", meaning: "〜を惜しげもなく配る・与える", level: 4 },
  { word: "drag on", phonetic: "/dræɡ ɑːn/", meaning: "（会議などが）ダラダラ長引く", level: 4 },
  { word: "egg on", phonetic: "/eɡ ɑːn/", meaning: "〜をそそのかしてけしかける", level: 4 },
  { word: "eke out", phonetic: "/iːk aʊt/", meaning: "〜を何とかやりくりして生計を立てる", level: 4 }
];
